import Head from 'next/head'
import NameAnimation from '@/NameAnimation'


export default function Home() {
  return (
    <>
      <Head>
        <title>ashish next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <NameAnimation />
      </main>
    </>
  )
}
