import Head from 'next/head'
import NameAnimation from '@/NameAnimation'


export default function Home() {
  return (
    <div>
      <Head>
        <title>ashish next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <NameAnimation />
      <h1> this is preview enivornment </h1>
      </main>
    </div>
  )
}
