name: Deploy to GitHub Pages

on:
 pull_request:
    branches:
      - dev
    types: [closed]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout dev
          git add .
          git commit -m "Deploy to GitHub Pages (Dev)"
         git push -f "https://$PAT_TOKEN@github.com/gitwithashishroy/codearoy.git" dev:gh-pages
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}